server:
  port: 7073

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnexus_recommendations
      database: fitnexus_recommendations

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  banner:
    location: banner.txt

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

rabbitmq:
  exchange:
    name: fitnexus.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
    key: AIzaSyASfPoym5WHNx5_h6AiiCXVPUP5Szraqjw