server:
  port: 7071

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitnexus_user_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  banner:
    location: banner.txt

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/